#!/bin/bash -e

if [ -z "${BUILDS+x}" ]; then
    BUILDS=("protoc-all" "protoc" "prototool" "grpc-cli" "gen-grpc-gateway")
fi
DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-namely}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${1:false}

DEBIAN_VERSION=${DEBIAN_VERSION:-trixie}
GO_VERSION=${GO_VERSION:-1.26.1}
GRPC_VERSION=${GRPC_VERSION:-1.80}
GRPC_JAVA_VERSION=${GRPC_JAVA_VERSION:-1.81}
GRPC_WEB_VERSION=${GRPC_WEB_VERSION:-2.0.2}
GRPC_GATEWAY_VERSION=${GRPC_GATEWAY_VERSION:-v2.29.0}
PROTOBUF_JS_VERSION=${PROTOBUF_JS_VERSION:-v4.0.2}
UBER_PROTOTOOL_VERSION=${UBER_PROTOTOOL_VERSION:-1.10.0}
SCALA_PB_VERSION=${SCALA_PB_VERSION:-0.11.0}
MYPY_VERSION=${MYPY_VERSION:-5.1.0}
NODE_VERSION=${NODE_VERSION:-24}
NODE_GRPC_TOOLS_NODE_PROTOC_TS_VERSION=${NODE_GRPC_TOOLS_NODE_PROTOC_TS_VERSION:-5.3.3}
NODE_GRPC_TOOLS_VERSION=${NODE_GRPC_TOOLS_VERSION:-1.13.1}
NODE_PROTOC_GEN_GRPC_WEB_VERSION=${NODE_PROTOC_GEN_GRPC_WEB_VERSION:-1.5.0}
TS_PROTO_VERSION=${TS_PROTO_VERSION:-2.11.8}
GO_ENVOYPROXY_PGV_VERSION=${GO_ENVOYPROXY_PGV_VERSION:-1.3.3}
GO_MWITKOW_GPV_VERSION=${GO_MWITKOW_GPV_VERSION:-0.3.2}
GO_PROTOC_GEN_GO_VERSION=${GO_PROTOC_GEN_GO_VERSION:-v1.36.11}
GO_PROTOC_GEN_GO_GRPC_VERSION=${GO_PROTOC_GEN_GO_GRPC_VERSION:-v1.6.2}
BUILD_VERSION="${BUILD_VERSION:-local}"
VERSION="${VERSION:-${GRPC_VERSION}_${BUILD_VERSION}}"
